import type {Metadata} from "next";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import "./theme-config.css";
import NavBar from "@/app/NavBar";
import {Theme} from "@radix-ui/themes";

import {Inter} from 'next/font/google';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={inter.variable}
        >
        <Theme accentColor="purple">
            <NavBar/>
            <main className="p-5">
                {children}
            </main>
        </Theme>
        </body>
        </html>
    );
}
